CREATE DATABASE burger_db;
USE burger_db;


CREATE TABLE Burgers (
	id INT AUTO_INCREMENT NOT NULL,
	name VARCHAR(255) NOT NULL,
	devoured TINYINT(1) DEFAULT '0',
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

